language: r
cache: packages
pandoc_version: 2.1

branches:
  only: source

script:
  - Rscript -e 'servr:::knit_maybe("_workbooks", "_analysis", "build.R", "jekyll")'
  
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_PAT
  on:
    branch: source
  target_branch: master
